---
title       : Assignement 2
subtitle    : Presentation of a shiny app
author      : JeanM
job         : 
framework   : html5slides        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Read-And-Delete

1. Edit YAML front matter
2. Write using R Markdown
3. Use an empty line followed by three dashes to separate slides!

--- .class #id 

## Slide 2
=======
test_R_presentation
========================================================
author: 
date: 

First Slide
========================================================

For more details on authoring R presentations click the
**Help** button on the toolbar.

---

Slide With Code
========================================================

```{r}
summary(cars)
```

---

Slide With Plot
========================================================

```{r, echo=FALSE}
plot(cars)
```
